"use client";

import { useEffect, useState } from "react";
import type { ReactNode } from "react";

type Meal = { id: string; name: string; restaurant: string; cuisine: string; price: number; emoji: string; tags: string[]; vibe: string; desc: string; season: string; spicy?: boolean; vegan?: boolean; glutenFree?: boolean; allergens?: string[] };

const meals: Meal[] = [
  { id: "miso-bowl", name: "Miso Salmon Glow Bowl", restaurant: "Kumo Kitchen", cuisine: "Japanese", price: 520, emoji: "🍣", tags: ["high protein", "umami", "omega-3"], vibe: "calm fuel", desc: "Miso-glazed salmon, edamame, roasted sweet potato and sesame greens over sushi rice.", season: "Monsoon", glutenFree: true, allergens: ["soy", "fish"] },
  { id: "ramen", name: "Midnight Tantanmen", restaurant: "Nori Club", cuisine: "Japanese", price: 460, emoji: "🍜", tags: ["spicy", "comfort", "sesame"], vibe: "late night", desc: "Silky sesame broth, springy noodles, chili crisp and a jammy egg.", season: "Monsoon", spicy: true, allergens: ["sesame", "wheat", "egg"] },
  { id: "taco", name: "Charred Corn Tacos", restaurant: "La Calle", cuisine: "Mexican", price: 380, emoji: "🌮", tags: ["fresh", "smoky", "shareable"], vibe: "sunny social", desc: "Three blue-corn tortillas with charred corn, avocado crema and chipotle mushrooms.", season: "Summer", vegan: true, glutenFree: true, spicy: true },
  { id: "paneer", name: "Tandoori Paneer Plate", restaurant: "Mitti", cuisine: "Indian", price: 420, emoji: "🍛", tags: ["comfort", "tandoor", "vegetarian"], vibe: "warm reset", desc: "Charred paneer, mint chutney, dal makhani and a crisp kachumber salad.", season: "Monsoon", spicy: true, glutenFree: true, allergens: ["dairy"] },
  { id: "salad", name: "Green Goddess Crunch", restaurant: "Field Notes", cuisine: "Modern", price: 340, emoji: "🥗", tags: ["light", "crunchy", "plant-powered"], vibe: "clear head", desc: "Little gem, herbs, quinoa, roasted chickpeas and a bright tahini dressing.", season: "Summer", vegan: true, glutenFree: true, allergens: ["sesame"] },
  { id: "pizza", name: "Hot Honey Margherita", restaurant: "Dough Theory", cuisine: "Italian", price: 490, emoji: "🍕", tags: ["cheesy", "sweet heat", "weekend"], vibe: "good chaos", desc: "Slow-fermented crust, tomato, fior di latte, basil and a drizzle of hot honey.", season: "Summer", spicy: true, allergens: ["dairy", "wheat"] },
];

const nav = [
  ["/", "Overview", "◒"], ["/discover", "Discover", "⌕"], ["/lab", "Food Lab", "✦"], ["/taste-dna", "Taste DNA", "◈"], ["/orders", "Orders", "↺"], ["/seasonal", "Seasonal", "❋"],
];

function score(meal: Meal) { const bonus = meal.tags.includes("high protein") ? 6 : 0; return Math.min(98, 78 + (meal.vibe === "calm fuel" ? 11 : 0) + bonus + (meal.glutenFree ? 2 : 0)); }
function Link({ href, children, className = "", onClick }: { href: string; children: ReactNode; className?: string; onClick?: (event: React.MouseEvent<HTMLAnchorElement>) => void }) {
  return <a className={className} href={href} onClick={(event) => { if (onClick) return onClick(event); event.preventDefault(); window.history.pushState({}, "", href); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo(0, 0); }}>{children}</a>;
}

export default function Home() { return <TasteForge />; }

export function TasteForge() {
  const [path, setPath] = useState(typeof window === "undefined" ? "/" : window.location.pathname);
  const [saved, setSaved] = useState<string[]>(() => { if (typeof window === "undefined") return []; const stored = localStorage.getItem("tasteforge-saved"); return stored ? JSON.parse(stored) : []; });
  const [toast, setToast] = useState("");
  const [filter, setFilter] = useState("All");
  useEffect(() => { const onPop = () => setPath(window.location.pathname); window.addEventListener("popstate", onPop); return () => window.removeEventListener("popstate", onPop); }, []);
  const go = (href: string) => { window.history.pushState({}, "", href); setPath(href); window.scrollTo(0, 0); };
  const save = (id: string) => { const next = saved.includes(id) ? saved.filter(x => x !== id) : [...saved, id]; setSaved(next); localStorage.setItem("tasteforge-saved", JSON.stringify(next)); setToast(saved.includes(id) ? "Removed from your shortlist" : "Saved to your shortlist"); setTimeout(() => setToast(""), 2200); };
  const view = path === "/" ? <Dashboard go={go} save={save} /> : path === "/discover" ? <Discover go={go} save={save} filter={filter} setFilter={setFilter} /> : path === "/lab" ? <FoodLab /> : path === "/taste-dna" ? <TasteDNA /> : path === "/orders" ? <Orders /> : path === "/seasonal" ? <Seasonal go={go} /> : path === "/surprise-me" ? <Surprise go={go} save={save} /> : <MealDetail id={path.split("/").pop() || "miso-bowl"} save={save} />;
  return <div className="app-shell"><aside className="sidebar"><Link href="/" className="brand" onClick={(e) => { e.preventDefault(); go("/"); }}><span className="brand-mark">TF</span><span>TasteForge<small>AI FOOD INTELLIGENCE</small></span></Link><div className="profile-chip"><div className="avatar">AR</div><div><b>Arjun Rao</b><span>Curious omnivore</span></div><i>⌄</i></div><nav>{nav.map(([href, label, icon]) => <a key={href} href={href} className={path === href ? "active" : ""} onClick={(e) => { e.preventDefault(); go(href); }}><span>{icon}</span>{label}{label === "Food Lab" && <em>NEW</em>}</a>)}</nav><div className="sidebar-bottom"><div className="mini-card"><span>✦</span><b>Your Taste DNA<br/><small>is 82% complete</small></b><strong>→</strong></div><a href="/surprise-me" className="surprise" onClick={(e) => { e.preventDefault(); go("/surprise-me"); }}>✧ Surprise me</a><span className="muted">v1.4 · crafted for curious eaters</span></div></aside><main className="main"><header><button className="mobile-brand" onClick={() => go("/")}>TF</button><div className="crumb">{path === "/" ? "Good evening, Arjun" : nav.find(x => x[0] === path)?.[1] || "Meal intelligence"}<span>·</span> <span className="muted">Mumbai · 7:42 PM</span></div><div className="header-actions"><button aria-label="Search">⌕</button><button aria-label="Notifications">♢<i className="dot" /></button><div className="avatar small">AR</div></div></header>{view}</main>{toast && <div className="toast">✓ {toast}</div>}</div>;
}

function PageTitle({ eyebrow, title, desc, action }: { eyebrow: string; title: string; desc: string; action?: ReactNode }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{action}</div>; }
function MealCard({ meal, save, featured = false }: { meal: Meal; save: (id: string) => void; featured?: boolean }) { return <article className={`meal-card ${featured ? "featured" : ""}`}><div className="meal-art"><span className="meal-emoji">{meal.emoji}</span><span className="match">{score(meal)}% match</span><button className="heart" onClick={() => save(meal.id)} aria-label="Save meal">♡</button></div><div className="meal-info"><div className="meal-meta">{meal.restaurant} <span>·</span> {meal.cuisine}</div><h3>{meal.name}</h3><p>{meal.tags.map(t => <span key={t}>{t}</span>)}</p><div className="meal-foot"><b>₹{meal.price}</b><Link href={`/meal/${meal.id}`}>See why →</Link></div></div></article>; }

function Dashboard({ go, save }: { go: (x: string) => void; save: (x: string) => void }) { return <div className="content"><section className="hero"><div><span className="eyebrow lime">PERSONALIZED FOR YOU</span><h1>Tonight, eat<br/><i>like yourself.</i></h1><p>Your taste is a moving target. We keep up. Here are three picks tuned to your mood, history and the Mumbai monsoon.</p><button className="primary" onClick={() => go("/surprise-me")}>Let AI surprise me <span>✦</span></button></div><div className="hero-orb"><div className="orb-core">✦<small>YOUR<br/>TASTE<br/>SIGNAL</small></div><span className="orb-label l1">UMAMI 92</span><span className="orb-label l2">CURIOUS 78</span><span className="orb-label l3">LIGHT 64</span></div></section><section className="section-head"><div><span className="eyebrow">THE SHORTLIST</span><h2>Made for your next bite</h2></div><button className="text-btn" onClick={() => go("/discover")}>View all picks →</button></section><div className="meal-grid">{meals.slice(0, 3).map((m, i) => <MealCard key={m.id} meal={m} save={save} featured={i === 0} />)}</div><section className="insight"><div className="insight-icon">✦</div><div><span className="eyebrow">TASTEFORGE INSIGHT</span><h3>You&apos;re in your “comfort, but make it interesting” era.</h3><p>Based on 14 orders, you lean toward familiar textures with one unexpected element. This week, try something smoky.</p></div><button onClick={() => go("/taste-dna")}>Explore my DNA →</button></section></div>; }

function Discover({ go, save, filter, setFilter }: { go: (x: string) => void; save: (x: string) => void; filter: string; setFilter: (x: string) => void }) { const filters = ["All", "High protein", "Vegetarian", "Vegan", "Under ₹400"]; const shown = meals.filter(m => filter === "All" || (filter === "High protein" && m.tags.includes("high protein")) || (filter === "Vegetarian" && !m.tags.includes("high protein")) || (filter === "Vegan" && m.vegan) || (filter === "Under ₹400" && m.price < 400)); return <div className="content"><PageTitle eyebrow="DISCOVER" title="Find your next obsession." desc="Every recommendation has a reason. Explore the signal behind the plate." action={<button className="outline" onClick={() => go("/surprise-me")}>✧ Surprise me</button>} /><div className="filter-row">{filters.map(f => <button className={filter === f ? "selected" : ""} key={f} onClick={() => setFilter(f)}>{f}</button>)}</div><div className="discover-grid">{shown.map(m => <MealCard key={m.id} meal={m} save={save} />)}</div></div>; }

function FoodLab() { const [mood, setMood] = useState("Focused"); const [spice, setSpice] = useState(2); return <div className="content"><PageTitle eyebrow="AI FOOD LAB" title="Cook up a recommendation." desc="Change the inputs. Watch your perfect plate appear." /><div className="lab-grid"><section className="lab-controls"><div className="control-label">What&apos;s the mood?</div><div className="mood-grid">{["Focused", "Treat myself", "Social", "Reset"].map(x => <button className={mood === x ? "selected" : ""} onClick={() => setMood(x)} key={x}>{x}</button>)}</div><label htmlFor="spice">Spice tolerance <b>{["Mild", "Warm", "Bold", "Fire"][spice]}</b></label><input id="spice" type="range" min="0" max="3" value={spice} onChange={e => setSpice(Number(e.target.value))} /><div className="control-label">Non-negotiables</div><div className="pills"><span>✓ No peanuts</span><span>✓ Gluten-friendly</span></div><button className="primary full">Generate my plate ✦</button></section><section className="lab-result"><div className="result-top"><span className="eyebrow lime">AI GENERATED · 0.8s</span><span className="confidence">94% confidence</span></div><div className="result-art">🍛</div><h2>Smoky Tofu Katsu Curry</h2><p>A crisp, plant-powered answer to your {mood.toLowerCase()} mood with {spice > 1 ? "a confident" : "a gentle"} chili finish.</p><div className="why"><b>Why this works for you</b><span>• Matches your love of umami</span><span>• Fits your weekday energy</span><span>• 31g protein · 640 kcal</span></div><button className="outline full">See the full recipe →</button></section></div></div>; }

function TasteDNA() { return <div className="content"><PageTitle eyebrow="YOUR TASTE DNA" title="A living map of your appetite." desc="Not a personality test. A pattern engine built from your real choices." /><div className="dna-layout"><section className="dna-card"><div className="dna-ring"><div><strong>82</strong><span>taste score</span></div></div><div className="dna-words"><span>CURIOUS</span><span>UMAMI-LED</span><span>TEXTURE SEEKER</span></div></section><section className="trait-list">{[["Umami",92,"#d5ff4a"],["Curiosity",78,"#ff875e"],["Comfort",71,"#7b7cff"],["Lightness",64,"#5ed9c4"]].map(([n,v,c]) => <div className="trait" key={String(n)}><div><b>{n}</b><strong>{v}%</strong></div><div className="bar"><i style={{ width: `${v}%`, background: String(c) }} /></div><small>{n === "Umami" ? "You chase the deep stuff." : n === "Curiosity" ? "You order one wildcard." : "Reliable, never boring."}</small></div>)}</section></div><div className="insight dark"><div className="insight-icon">✦</div><div><span className="eyebrow lime">NEXT EVOLUTION</span><h3>Your palate is ready for more fermentation.</h3><p>Try kimchi, koji or a naturally funky cheese this week to grow your discovery score.</p></div></div></div>; }

function Orders() { return <div className="content"><PageTitle eyebrow="ORDER HISTORY" title="Your edible memory." desc="Every order teaches TasteForge a little more about you." /><div className="stats"><div><strong>14</strong><span>orders analyzed</span></div><div><strong>4.8<span>/5</span></strong><span>average rating</span></div><div><strong>₹6.2k</strong><span>joy invested</span></div></div><div className="order-list">{[["Yesterday","Miso Salmon Glow Bowl","Kumo Kitchen","🍣","Loved it"],["12 Aug","Tandoori Paneer Plate","Mitti","🍛","Would reorder"],["08 Aug","Charred Corn Tacos","La Calle","🌮","New favorite"],["02 Aug","Hot Honey Margherita","Dough Theory","🍕","Good chaos"]].map(o => <div className="order-row" key={String(o[1])}><span className="order-date">{o[0]}</span><span className="order-thumb">{o[3]}</span><div><b>{o[1]}</b><small>{o[2]}</small></div><span className="order-tag">{o[4]}</span><span>→</span></div>)}</div></div>; }

function Seasonal({ go }: { go: (x: string) => void }) { return <div className="content"><PageTitle eyebrow="SEASONAL SIGNAL" title="The monsoon edit." desc="Rain outside. Warm, bright, deeply satisfying food inside." /><div className="season-hero"><div><span className="eyebrow lime">CURATED FOR MUMBAI · AUGUST</span><h2>Comfort with<br/><i>a little weather.</i></h2><p>Our seasonal engine is reading the room: cozy broths, tandoor smoke, and enough brightness to keep things buoyant.</p><button className="primary" onClick={() => go("/discover")}>Explore the edit →</button></div><div className="rain-art">☔<span>☁</span><span>☁</span></div></div><div className="section-head"><div><span className="eyebrow">IN SEASON NOW</span><h2>Rainy-day energy</h2></div></div><div className="meal-grid">{meals.filter(m => m.season === "Monsoon").map(m => <MealCard key={m.id} meal={m} save={() => {}} />)}</div></div>; }

function Surprise({ go, save }: { go: (x: string) => void; save: (x: string) => void }) { const [step, setStep] = useState(0); return <div className="content surprise-page"><div className="surprise-panel"><span className="eyebrow lime">THE WILDCARD ENGINE</span>{step === 0 ? <><h1>Let&apos;s make<br/><i>tonight interesting.</i></h1><p>We&apos;ll balance your taste DNA with one beautiful left turn. No random picks. Just the right kind of unexpected.</p><button className="primary" onClick={() => setStep(1)}>Find my wildcard ✦</button></> : <><span className="eyebrow lime">YOUR WILDCARD IS READY</span><div className="wild-art">🌮</div><h1>Charred Corn Tacos</h1><p>86% match · Your curiosity score made the call. Smoky, plant-powered, and just outside your usual lane.</p><button className="primary" onClick={() => { save("taco"); go("/meal/taco"); }}>I&apos;m into it →</button><button className="text-btn" onClick={() => setStep(0)}>Try another</button></>}</div></div>; }

function MealDetail({ id, save }: { id: string; save: (x: string) => void }) { const meal = meals.find(m => m.id === id) || meals[0]; return <div className="content"><Link href="/discover" className="back">← Back to discover</Link><div className="detail-grid"><div className="detail-art">{meal.emoji}<span className="match big">{score(meal)}% match</span></div><div className="detail-copy"><span className="eyebrow">{meal.restaurant} · {meal.cuisine}</span><h1>{meal.name}</h1><p className="lead">{meal.desc}</p><div className="reason-box"><b>✦ TasteForge says</b><p>This hits your umami preference, keeps the texture interesting, and stays inside your current food goals.</p></div><div className="detail-price"><strong>₹{meal.price}</strong><button className="primary" onClick={() => save(meal.id)}>Save for later ♡</button></div></div></div></div>; }
